name: admin
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.3.2+1
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.4+1
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.0+1
  flutter_html: ^0.11.1
  http: ^0.12.0+4
  intl: ^0.16.1
  line_icons: ^0.2.0
  provider: ^4.3.2
  shared_preferences: ^0.5.12
  toast: ^0.1.5
  url_launcher: ^5.7.2
  vertical_tabs: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  fonts:

    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Light.ttf
          weight: 400
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 500
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 600
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800

  assets:

    - assets/images/icon.png
